before:
  hooks:
    - make goreleaser_verify
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    targets:
      - linux_amd64
      - linux_386
      - linux_arm64
      - linux_arm_6
      - linux_arm_7
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_386
      - windows_arm64
      - windows_arm_6
      - windows_arm_7
archives:
  - format: tar.xz
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  draft: true
  discussion_category_name: Releases
  prerelease: auto
  mode: keep-existing
